# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' #Makes sense, we are testing against master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup Zig
      # You may pin to the exact commit or the version.
      # uses: goto-bus-stop/setup-zig@41ae19e72e21b9a1380e86ff9f058db709fc8fc6
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
          
      - run: zig version
      - run: zig env
      
      - name: Build
        run: zig build

      - name: Run Tests
        run: zig build test

      - name: Create Wasm Example
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: | 
          mv docs docs2 
        
      - name: Minimify Page export
        uses: zugazagoitia/minify-js@v0.4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          directory: docs2/index.html # Who puts directory for a file =)

      - name: Deploy Github Pages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: docs2
